"""Hardware backends. `real` drives the arms through LeRobot; `fake` simulates them."""

from pathlib import Path
from typing import Protocol

import numpy as np


class Dataset(Protocol):
    num_episodes: int

    def save_episode(self) -> None: ...
    def clear_episode_buffer(self) -> None: ...
    def finalize(self, error: BaseException | None = None) -> None: ...


class Policy(Protocol):
    def reset(self) -> None: ...


class Backend(Protocol):
    """Everything the modes need from the robot.

    `events` is LeRobot's control dict: loops return when events["exit_early"] is set
    (and clear it), or when `seconds` run out.
    """

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def frame(self, camera: str) -> np.ndarray | None: ...
    def teleop(self, seconds: float, events: dict) -> None: ...
    def record(self, dataset: Dataset, seconds: float, events: dict, task: str) -> None: ...
    def open_dataset(self, root: Path, task: str) -> Dataset: ...
    def load_policy(self, path: Path) -> Policy: ...
    def drive(self, policy: Policy, events: dict, task: str) -> None: ...
